package com.resistance.mvc.auth;

import com.resistance.shared.utils.crypto.AesGcmFieldEncryptor;
import com.resistance.shared.utils.crypto.FieldEncryptors;
import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;

import java.util.Base64;

/**
 * Activates PII field encryption when a data key is configured. The key is
 * generated by AWS KMS and injected base64-encoded via TRACKER_ENC_KEY -
 * see infrastructure/aws/README.md. Without a key (dev) fields stay
 * plaintext and a warning is logged.
 */
@Configuration
public class EncryptionConfig {

    private static final Logger log = LoggerFactory.getLogger(EncryptionConfig.class);

    @Value("${tracker.encryption.key:}")
    private String base64Key;

    @PostConstruct
    public void configureFieldEncryption() {
        if (base64Key == null || base64Key.isBlank()) {
            log.warn("tracker.encryption.key not set - PII fields are stored in PLAINTEXT (dev mode)");
            return;
        }
        FieldEncryptors.use(new AesGcmFieldEncryptor(Base64.getDecoder().decode(base64Key.trim())));
        log.info("PII field encryption enabled (AES-256-GCM, KMS-sourced data key)");
    }
}
